selected_cols <- c("Region", "Country", "Submeasure")
flat_data[,match(selected_cols,names(flat_data))] <- lapply(flat_data[,match(selected_cols,names(flat_data))], as.character)
# flat_data$Region <- as.character(flat_data$Region)
# flat_data$Country <- as.character(flat_data$Country)
# flat_data$Submeasure <- as.character(flat_data$Submeasure)
selected_cols <- c("variable", "TV.households", "Installed.base", "Domestic.consumption", "Shipments", "Revenues")
flat_data[,match(selected_cols,names(flat_data))] <- lapply(flat_data[,match(selected_cols,names(flat_data))], f2n)
# flat_data$variable <- f2n(flat_data$variable)
# flat_data$TV.households <- f2n(flat_data$TV.households)
# flat_data$Installed.base <- f2n(flat_data$Installed.base)
# flat_data$Domestic.consumption <- f2n(flat_data$Domestic.consumption)
# flat_data$Shipments <- f2n(flat_data$Shipments)
# flat_data$Revenues <- f2n(flat_data$Revenues)